### ISSUE TITLE
docker swarm - Can't find DB

### ISSUE THREAD

**Issue by A1994SC** [xbrowsersync/api#61]
I am having issues with my stack being deployed to but the api can not find the mongodb server (both within the scope of the mongo stack and outside).   
The following is the error being thrown by the xbs_api containter:
```
{
  "name": "xBrowserSync_api",
  "hostname": "7d8549e34a6b",
  "pid": 1,
  "level": 50,
  "req": null,
  "err": {
    "message": "Authentication failed.",
    "name": "MongoError",
    "stack": "MongoError: Authentication failed.
		at MessageStream.messageHandler (/usr/src/api/node_modules/mongodb/lib/cmap/connection.js:268:20)
		at MessageStream.emit (events.js:315:20)
		at processIncomingData (/usr/src/api/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
		at MessageStream._write (/usr/src/api/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
		at writeOrBuffer (internal/streams/writable.js:358:12)
		at MessageStream.Writable.write (internal/streams/writable.js:303:10)
		at Socket.ondata (internal/streams/readable.js:719:22)
		at Socket.emit (events.js:315:20)
		at addChunk (internal/streams/readable.js:309:12)
		at readableAddChunk (internal/streams/readable.js:284:9)
		at Socket.Readable.push (internal/streams/readable.js:223:10)
		at TCP.onStreamRead (internal/stream_base_commons.js:188:23)",
    "code": 18
  },
  "msg": "Unable to connect to database",
  "time": "2021-05-16T04:28:08.200Z",
  "v": 0
}
```

The xbs-stack.yml
```
version: "3.8"
services:
  api:
    image: "xbrowsersync/api:1.1.13"
    volumes:
      - xbs_data:/usr/src/api/
    ports:
      - 8082:8080
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.xbs.entrypoints=http"
        - "traefik.http.middlewares.xbs-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.xbs.middlewares=xbs-https-redirect"
        - "traefik.http.routers.xbs-secure.entrypoints=https"
        - "traefik.http.routers.xbs-secure.tls=true"
        - "traefik.http.routers.xbs-secure.service=xbs"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.xbs.rule=Host(`xbs.in.derpaholic.com`)"
        - "traefik.http.routers.xbs-secure.rule=Host(`xbs.in.derpaholic.com`)"
        - "traefik.http.services.xbs.loadbalancer.server.port=8080"
      placement:
         constraints:
           - node.labels.xbs.settings==true
    networks:
      - proxy
    healthcheck:
      test: [ "CMD", "node", "/usr/src/api/healthcheck.js" ]
      interval: "1m"
      timeout: "10s"
      retries: 5
      start_period: "30s"
volumes:
  xbs_data:
networks:
  proxy:
    external: true
```
Lastly the setting.json
```
{
    "db": {
        "host": "mongodb_mongodb",
        "name": "xbrowsersync",
        "username": "xbs",
        "password": "<password>"
    },
    "maxSyncs": 1,
    "maxSyncSize": 10240000,
    "status": {
        "allowNewSyncs": true,
        "message": "xBrowserSync."
    }
}
```
worth noting that "mongodb_mongodb" does work as the host because that is the hostname of the mongo server within the swarm. I have tested that within a ubuntu container attached to the same network.   

Thank you for any help!
